export default [
 {
   "Name": "Wilaiwan (วิไลวรรณ)",
   "Location": "หัวหิน",
   "Position": "12.535267, 99.965066",
   "Category": "Restaurant",
   "Sub-category": "Café/Dessert",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "21:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/27156lk-wilaiwan-%E0%B8%AB%E0%B8%B1%E0%B8%A7%E0%B8%AB%E0%B8%B4%E0%B8%99?ref=ct",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R002_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "บ้านอิสระ (Baan Itsara)",
   "Location": "หัวหิน",
   "Position": "12.582358, 99.955671",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "23:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/916Tg-%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AD%E0%B8%B4%E0%B8%AA%E0%B8%A3%E0%B8%B0?ref=ct",
   "Fee": "501-1000",
   "Time spent": "0:50",
   "Picture": "R003_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "บ้านใกล้วัง (Bann Gliwang)",
   "Location": "หัวหิน",
   "Position": "12.581583, 99.955639",
   "Category": "Restaurant",
   "Sub-category": "Café/Dessert",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "21:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/baangliwang?ref=ct",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R004_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "โกทิ (Ko Thi) หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.571466, 99.956743",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "12:00",
   "Close": "22:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/942eY-%E0%B9%82%E0%B8%81%E0%B8%97%E0%B8%B4-%E0%B8%AB%E0%B8%B1%E0%B8%A7%E0%B8%AB%E0%B8%B4%E0%B8%99",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R005_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "La Villa (ลาวิลล่า) หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.568977, 99.958875",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:30",
   "Close": "22:30",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/8485qN-la-villa-%E0%B8%AB%E0%B8%B1%E0%B8%A7%E0%B8%AB%E0%B8%B4%E0%B8%99?ref=ct",
   "Fee": "251-500",
   "Time spent": "0:50",
   "Picture": "R006_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ป้าพร น้องหยก (Pa Pon Nong Yok)",
   "Location": "หัวหิน",
   "Position": "12.516489, 99.979132",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "7:00",
   "Close": "21:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/papornnongyok?ref=ct",
   "Fee": "251-500",
   "Time spent": "0:50",
   "Picture": "R007_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "แสงไทย ซีฟู้ด (Sang Thai Seafood)",
   "Location": "หัวหิน",
   "Position": "12.574098, 99.959364",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "22:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/940yD-%E0%B9%81%E0%B8%AA%E0%B8%87%E0%B9%84%E0%B8%97%E0%B8%A2-%E0%B8%8B%E0%B8%B5%E0%B8%9F%E0%B8%B9%E0%B9%89%E0%B8%94?ref=ct",
   "Fee": "501-1000",
   "Time spent": "0:50",
   "Picture": "R008_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "XXL Kitchen Hua Hin 10 (เอ็กซ์ เอ็กซ์ แอล คิทเช่น หัวหิน)",
   "Location": "หัวหิน",
   "Position": "12.609780, 99.949911",
   "Category": "Restaurant",
   "Sub-category": "American",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "12:00",
   "Close": "20:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/15625sL-xxl-kitchen-hua-hin-10?ref=ct",
   "Fee": "501-1000",
   "Time spent": "0:50",
   "Picture": "R009_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "บ้านถั่วเย็น",
   "Location": "หัวหิน",
   "Position": "12.578716, 99.956089",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "20:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/%E0%B8%B4baantuayen",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R010_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "อยู่เย็น (Youyen) หัวหิน บัลโคนี่",
   "Location": "หัวหิน",
   "Position": "12.580220,99.956425",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "22:30",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/943Yx-%E0%B8%AD%E0%B8%A2%E0%B8%B9%E0%B9%88%E0%B9%80%E0%B8%A2%E0%B9%87",
   "Fee": "251-500",
   "Time spent": "0:50",
   "Picture": "R011_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ร้านครัวบ้านครู",
   "Location": "หัวหิน",
   "Position": "12.388451,99.927387",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "21:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/888eq-%E0%B8%84%E0%B8%A3%E0%B8%B1%E0%B8%A7%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%B9?ref=ct",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R012_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "บ้านปูเป็น (Baan Poo Phen)",
   "Location": "หัวหิน",
   "Position": "12.517901,99.976253",
   "Category": "Restaurant",
   "Sub-category": "Seafood",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "10:00",
   "Close": "23:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/915wT-%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%9B%E0%B8%B9%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99?ref=ct",
   "Fee": "251-500",
   "Time spent": "0:50",
   "Picture": "R013_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ครัวกรรณิการ์ (KHRUA KANNIKA RESTAURANT)",
   "Location": "หัวหิน",
   "Position": "12.563433,99.955968",
   "Category": "Restaurant",
   "Sub-category": "Thai",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "22:30",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/11304af-%E0%B8%84%E0%B8%A3%E0%B8%B1%E0%B8%A7%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%93%E0%B8%B4%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%8C?ref=ct",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R014_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "เปิ้ล ซีฟู้ด (Ple Seafood)",
   "Location": "หัวหิน",
   "Position": "12.51338,99.978833",
   "Category": "Restaurant",
   "Sub-category": "Thai",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "21:00",
   "Tel": "",
   "Facebook": "",
   "Website": "https://www.wongnai.com/restaurants/9688dR-%E0%B9%80%E0%B8%9B%E0%B8%B4%E0%B9%89%E0%B8%A5-%E0%B8%8B%E0%B8%B5%E0%B8%9F%E0%B8%B9%E0%B9%89%E0%B8%94?ref=ct",
   "Fee": "101-250",
   "Time spent": "0:50",
   "Picture": "R015_01.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "อุทยานราชภักดิ์",
   "Location": "หัวหิน",
   "Position": "12.5009874,99.9666093",
   "Category": "Education",
   "Sub-category": "Museaum",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "18:00",
   "Tel": "",
   "Facebook": "",
   "Website": "www.rta.mi.th",
   "Fee": "Free",
   "Time spent": "1:30",
   "Picture": "P001_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ชายหาดหัวหิน",
   "Location": "หัวหิน",
   "Position": "12.569538, 99.962785",
   "Category": "Nature",
   "Sub-category": "Beach",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "N/A",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Not yet",
   "Time spent": "",
   "Picture": "P002_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ตลาดโต้รุ่ง",
   "Location": "หัวหิน",
   "Position": "12.571108, 99.955472",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "18:00",
   "Close": "0:00:00",
   "Tel": "063 585 2350",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "1.30-3.00",
   "Picture": "P003_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "สถานีรถไฟหัวหิน",
   "Location": "หัวหิน",
   "Position": "12.567333, 99.954695",
   "Category": "Culture",
   "Sub-category": "History",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "18:00",
   "Close": "0:00:00",
   "Tel": "0 3251 1073",
   "Facebook": "",
   "Website": "",
   "Fee": "Not yet",
   "Time spent": "1.00-2.00",
   "Picture": "P004_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "Venezia Huahin",
   "Location": "หัวหิน",
   "Position": "12.649965, 99.951181",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "20:00",
   "Tel": "095 369 9359",
   "Facebook": "www.facebook.com/The Venezia Hua Hin and theveneziahuahin.com",
   "Website": "",
   "Fee": "More datail",
   "Time spent": "1.30-3.00",
   "Picture": "P005_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ตลาดน้ำหัวหินสามพันนาม",
   "Location": "หัวหิน",
   "Position": "12.501146, 99.915058",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "20:00",
   "Tel": "08 1457 8888,032 900 111",
   "Facebook": "www.facebook.com/Huahin Samphannam Floatingmarket",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "1.00-2.00",
   "Picture": "P006_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "Huahintique Animal Show",
   "Location": "หัวหิน",
   "Position": "12.510190, 99.920229",
   "Category": "Recreation",
   "Sub-category": "Zoo",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "20:00",
   "Tel": "032 510 222, 09 2727 1122, 08 0240 5555",
   "Facebook": "",
   "Website": "hua-hintique.com",
   "Fee": "Not yet",
   "Time spent": "3.00-4.00",
   "Picture": "P007_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ตลาดเพลินวาน",
   "Location": "หัวหิน",
   "Position": "12.594167, 99.949138",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "10:00",
   "Close": "22:00",
   "Tel": "032 520 311",
   "Facebook": "www.facebook.com/Plearnwan Hua Hin",
   "Website": "plearnwan.com",
   "Fee": "Varies",
   "Time spent": "1.00-2.00",
   "Picture": "P008_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "The Cicada Market",
   "Location": "หัวหิน",
   "Position": "12.534429, 99.966042",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Fr Sa Su",
   "Open": "16:00",
   "Close": "23:00",
   "Tel": "0 3253 6606, 08 0650 4334, 08 1880 4004",
   "Facebook": "www.facebook.com/cicadahuahin",
   "Website": "cicadamarket.com",
   "Fee": "Varies",
   "Time spent": "1.30-3.00",
   "Picture": "P009_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "วัดห้วยมงคล",
   "Location": "หัวหิน",
   "Position": "12.552556,99.824345",
   "Category": "Culture",
   "Sub-category": "Temple",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "17:00",
   "Close": "21:00",
   "Tel": "0 3257 6187, 0 3257 6297",
   "Facebook": "",
   "Website": "",
   "Fee": "0-200",
   "Time spent": "0.30-1.30",
   "Picture": "P010_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ตลาดฉัตรไชย",
   "Location": "หัวหิน",
   "Position": "12.571523, 99.956396",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "5:00",
   "Close": "18:00",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "1.00-2.00",
   "Picture": "P011_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "สวนสนประดิพัทธ์",
   "Location": "หัวหิน",
   "Position": "12.5009874,99.9666093",
   "Category": "Recreation,Nature",
   "Sub-category": "Garden",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "17:00",
   "Tel": "03253 6581, 08 1986 6984",
   "Facebook": "",
   "Website": "suanson.infantry-center.com",
   "Fee": "Not yet",
   "Time spent": "2.00-4.00",
   "Picture": "P012_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ฟาร์มแกะดำ หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.532632, 99.836992",
   "Category": "Agriculture",
   "Sub-category": "Farm",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "17:00",
   "Tel": "08 8760 2804",
   "Facebook": "www.facebook.com/ Black Sheep Huahin Fun Farm",
   "Website": "",
   "Fee": "",
   "Time spent": "1.00-3.00",
   "Picture": "P013_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ไร่องุ่นหัวหินฮิลส์ วินยาร์ด",
   "Location": "หัวหิน",
   "Position": "12.525808, 99.705454",
   "Category": "Agriculture",
   "Sub-category": "Crop",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "9:00",
   "Close": "17:00",
   "Tel": "08 1701 0222, 08 1701 0444, 08 1701 8874, 08 1701 8875",
   "Facebook": "",
   "Website": "huahinhills.com",
   "Fee": "0-100",
   "Time spent": "1.00-3.00",
   "Picture": "P014_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "ตลาดฉัตรศิลา",
   "Location": "หัวหิน",
   "Position": "12.571146, 99.956188",
   "Category": "Recreation",
   "Sub-category": "Market",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "17:00",
   "Close": "23:00",
   "Tel": "",
   "Facebook": "www.facebook.com/Chatsila",
   "Website": "",
   "Fee": "varies",
   "Time spent": "1.00-3.00",
   "Picture": "P015_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "Black Mountain Water Park",
   "Location": "หัวหิน",
   "Position": "12.604165, 99.889424",
   "Category": "Recreation",
   "Sub-category": "Amusement",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "10:00",
   "Close": "17:00",
   "Tel": "0 3261 8444",
   "Facebook": "www.facebook.com/Blackmountainwaterpark",
   "Website": "lackmountainwaterpark.com",
   "Fee": "300-1000",
   "Time spent": "4.00-6.00",
   "Picture": "P016_003.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "น้ำตกป่าละอู",
   "Location": "หัวหิน",
   "Position": "12.538111, 99.463532",
   "Category": "Nature",
   "Sub-category": "Waterfall",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "17:00",
   "Tel": "08 7161 2922",
   "Facebook": "",
   "Website": "park.dnp.go.th",
   "Fee": "20-40",
   "Time spent": "2.00-4.00",
   "Picture": "P017_003.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "Vana Nava Hua Hin Water Park",
   "Location": "หัวหิน",
   "Position": "12.532427, 99.962089",
   "Category": "Recreation",
   "Sub-category": "Amusement",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "10:00",
   "Close": "17:00",
   "Tel": "0 3290 9606",
   "Facebook": "https://www.facebook.com/VanaNavaHuaHin",
   "Website": "vananavahuahin.com",
   "Fee": "600-1000",
   "Time spent": "4.00-6.00",
   "Picture": "P018_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "Seenspace Hua Hin",
   "Location": "หัวหิน",
   "Position": "12.597220, 99.954454",
   "Category": "Recreation",
   "Sub-category": "Seesighting",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "10:00",
   "Close": "22:00",
   "Tel": "www.facebook.com/Seenspace huahin",
   "Facebook": "seenspace.com",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "1.00-3.00",
   "Picture": "P019_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "รฤก หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.579175, 99.955957",
   "Category": "Recreation",
   "Sub-category": "Walking Street",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "11:00",
   "Close": "22:00",
   "Tel": "www.facebook.com/ RarukHuaHin",
   "Facebook": "rarukhuahin.com",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "1.00-3.00",
   "Picture": "P020_002.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "หาดเขาตะเกียบ",
   "Location": "หัวหิน",
   "Position": "12.515822, 99.981682",
   "Category": "Nature",
   "Sub-category": "Beach",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "22:00",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "2.00-4.00",
   "Picture": "P021_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "หาดเขาเต่า",
   "Location": "หัวหิน",
   "Position": "12.458035, 99.979064",
   "Category": "Nature",
   "Sub-category": "Beach",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "22:00",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "2.00-4.00",
   "Picture": "P022_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "หาดทรายน้อย",
   "Location": "หัวหิน",
   "Position": "12.458035, 99.979064",
   "Category": "Nature",
   "Sub-category": "Beach",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "20:00",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "2.00-4.00",
   "Picture": "P023_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "หาดชะอำ",
   "Location": "หัวหิน",
   "Position": "12.794190, 99.984274",
   "Category": "Nature",
   "Sub-category": "Beach",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "8:00",
   "Close": "20:00",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "Varies",
   "Time spent": "2.00-4.00",
   "Picture": "P024_001.jpg",
   "Date added": "2/4/2560"
 },
 {
   "Name": "โรงแรม หินน้ำทรายสวย",
   "Location": "หัวหิน",
   "Position": "12.615723,99.950688",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1800-2400",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "อัสสรา วิลล่า แอนด์ สวีท",
   "Location": "หัวหิน",
   "Position": "12.616522,99.95276",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "8000-900",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "ฮาเว่น รีสอร์ท หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.639933,99.955231",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "3900-4200",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "โรงแรม เดอะซีเคร็ท หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.551238,99.963210",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "3600-4300",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "เรส ดีเทล หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.6044299, 99.954345",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "6900-7400",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "The Imperial Hua Hin Beach",
   "Location": "หัวหิน",
   "Position": "12.598752, 99.954964",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "2400-2600",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Hilton Hua Hin Resort & Spa",
   "Location": "หัวหิน",
   "Position": "12.570659,99.960953",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "7600-7800",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Marrakesh Hua Hin Resort & Spa",
   "Location": "หัวหิน",
   "Position": "12.544238 , 99.964419",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "6000-6500",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Sukkasem Guesthouse",
   "Location": "หัวหิน",
   "Position": "12.572326, 99.959950",
   "Category": "Residence",
   "Sub-category": "Guesthouse",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1300-1500",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Mod Guest House",
   "Location": "หัวหิน",
   "Position": "12.571981, 99.960416",
   "Category": "Residence",
   "Sub-category": "Guesthouse",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "800-1000",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "โรงแรม บ้านนิลวรรณ หัวหิน Baan Nilawan Hua Hin Hotel",
   "Location": "หัวหิน",
   "Position": "12.599979, 99.950941",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1200-1400",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "โรงแรมบ้านมัณฑนา",
   "Location": "หัวหิน",
   "Position": "12.570044, 99.956103",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "2600-2900",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "ธนวิทย์โฮเทลแอนด์สปา",
   "Location": "หัวหิน",
   "Position": "12.569250, 99.956109",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1700-1900",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "โรงแรม พุทธรักษา หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.5772621,99.956182",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "7600-7800",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Ayrest Hotel 华欣",
   "Location": "หัวหิน",
   "Position": "12.609819, 99.949754",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "2400-2700",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Laksasubha Hua Hin",
   "Location": "หัวหิน",
   "Position": "12.566113,99.960372",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "4400-4600",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "The Palayan Hua Hin",
   "Location": "หัวหิน",
   "Position": "12.666533, 99.957136",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "4250-4500",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "The Hideaway Resort",
   "Location": "หัวหิน",
   "Position": "12.611537,99.952691",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1600-1800",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "I-Style HuaHin",
   "Location": "หัวหิน",
   "Position": "12.603225,99.951588",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "800-1000",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Asara Villa&suite",
   "Location": "หัวหิน",
   "Position": "12.619971,99.952659",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "6800-7000",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Hyatt Regency Hua Hin",
   "Location": "หัวหิน",
   "Position": "12.6536024,99.967378",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "8800-8900",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Sheraton Hua Hin Resort & Spa",
   "Location": "หัวหิน",
   "Position": "12.665473, 99.956507",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "5100-5300",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Dusit Thani Hua Hin",
   "Location": "หัวหิน",
   "Position": "12.657736,99.956179",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "4200-4600",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Novotel Hua Hin Cha Am Beach Resort and Spa",
   "Location": "หัวหิน",
   "Position": "12.721845,99.961847",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "2100-2300",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "อาคา กุฏิ รีสอร์ท หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.597958, 99.908143",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "4800-5000",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "เทวัญ ดารา รีสอร์ทแอนด์สปา หัวหิน",
   "Location": "หัวหิน",
   "Position": "12.582525, 99.857670",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "3500-3700",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Black Lotus Resort & Spa",
   "Location": "หัวหิน",
   "Position": "12.512305, 99.931796",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "2400-2700",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Hotel V Villas Hua Hin MGallery by Sofitel",
   "Location": "หัวหิน",
   "Position": "12.543111, 99.963906",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "19300-19600",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "InterContinental Hua Hin Resort",
   "Location": "หัวหิน",
   "Position": "12.548963, 99.964237",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "6250-6500",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "City Beach Resort",
   "Location": "หัวหิน",
   "Position": "12.568926, 99.958633",
   "Category": "Residence",
   "Sub-category": "Resort",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "1700-1900",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 },
 {
   "Name": "Baan Duangkaew Resort Hotel",
   "Location": "หัวหิน",
   "Position": "12.534379, 99.967300",
   "Category": "Residence",
   "Sub-category": "Hotel",
   "Detail": "",
   "Available Day": "Everyday",
   "Open": "",
   "Close": "",
   "Tel": "",
   "Facebook": "",
   "Website": "",
   "Fee": "3900-4100",
   "Time spent": "",
   "Picture": "",
   "Date added": ""
 }
];
